apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-practice-app
  labels:
    app: secure-practice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secure-practice
  template:
    metadata:
      labels:
        app: secure-practice
    spec:
      containers:
        - name: app
          image: ghcr.io/OWNER/secure-cicd-practice:latest
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 20
