name: CI/CD pipeline
on:
  push:
    branches: [ main ]
  workflow_dispatch:
env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/secure-cicd-practice
jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - id: tag
        run: echo "::set-output name=tag::${GITHUB_SHA::8}"
      - run: docker build -t $IMAGE_NAME:${{ steps.tag.outputs.tag }} -f Dockerfile .
      - run: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin && syft $IMAGE_NAME:${{ steps.tag.outputs.tag }} -o json > sbom.json
      - run: docker push $IMAGE_NAME:${{ steps.tag.outputs.tag }}
      - uses: actions/upload-artifact@v4
        with:
          name: sbom-${{ steps.tag.outputs.tag }}
          path: sbom.json
  deploy-staging:
    needs: build-and-scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-kubectl@v3
        with:
          version: 'v1.26.0'
      - run: echo "${{ secrets.KUBECONFIG_B64 }}" | base64 --decode > kubeconfig
      - run: kubectl apply -f k8s/
